import { useEffect, useMemo } from 'react'
import { createPortal } from 'react-dom'
import type { Defect } from '../api'
import { analyzeUnit } from '../defectGroups'
import type { Kind } from '../truckZones'

export interface SummaryRow {
  unit: string
  kind: string
  company: string
  status: Record<string, number>
  records: Defect[]
}

function fmtDate(d: Date): string {
  return d.toLocaleString(undefined, {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })
}

function SummaryUnit({ row }: { row: SummaryRow }) {
  const kind: Kind = row.kind === 'trailer' ? 'trailer' : 'truck'
  const { groups } = useMemo(
    () => analyzeUnit(row.records, kind), [row.records, kind])
  const open = row.status.Open ?? 0
  const total = groups.reduce((s, g) => s + g.count, 0)

  return (
    <li className="sr-unit">
      <div className="sr-uhead">
        <span className="sr-ucode">{row.unit}</span>
        <span className="sr-ukind">{kind}</span>
        <span className="sr-uco">{row.company}</span>
        <span className="sr-uopen">Open {open}</span>
        <span className="sr-utot">
          {groups.length} defect{groups.length === 1 ? '' : 's'}
          {total > groups.length ? ` · ${total} reports` : ''}
        </span>
      </div>
      {groups.length === 0 ? (
        <p className="sr-empty">No real defects.</p>
      ) : (
        <ul className="sr-defs">
          {groups.map((g, i) => (
            <li key={i}>
              <span className="sr-cat">{g.category}</span>
              {g.body && <span className="sr-body"> · {g.body}</span>}
              {g.count > 1 && <em className="sr-rep"> ×{g.count}</em>}
            </li>
          ))}
        </ul>
      )}
    </li>
  )
}

export default function SummaryReport(
  { rows, scope, onClose }: {
    rows: SummaryRow[]; scope: string; onClose: () => void
  },
) {
  const generated = useMemo(() => fmtDate(new Date()), [])
  const totalDefects = useMemo(
    () => rows.reduce((s, r) => s + (r.status.Open ?? 0), 0), [rows])

  useEffect(() => {
    const done = () => onClose()
    window.addEventListener('afterprint', done, { once: true })
    const t = window.setTimeout(() => window.print(), 120)
    return () => {
      window.clearTimeout(t)
      window.removeEventListener('afterprint', done)
    }
  }, [onClose])

  return createPortal(
    <div className="print-root">
      <div className="summary-report" data-theme="light">
        <header className="sr-head">
          <div className="ur-brand">
            <img src="/favicon.svg" alt="" className="ur-logo" />
            <div>
              <span className="ur-brand-name">Rigsmith</span>
              <span className="ur-brand-sub">DVIR compliance</span>
            </div>
          </div>
          <div className="ur-title">
            <h1>Open Defects · Summary</h1>
            <span className="ur-gen">
              {scope} · {rows.length} units · {totalDefects} open ·
              {' '}Generated {generated}
            </span>
          </div>
        </header>

        <ol className="sr-list">
          {rows.map((r) => <SummaryUnit key={r.unit} row={r} />)}
        </ol>

        <footer className="sr-foot">
          Generated by Rigsmith · {generated} · Internal use only.
        </footer>
      </div>
    </div>,
    document.body,
  )
}
