"""initial schema

Revision ID: a518e3d89977
Revises: 
Create Date: 2026-06-18 05:41:30.697286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a518e3d89977'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_slug'), ['slug'], unique=True)

    op.create_table('poi',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('subtype', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('brand', sa.String(length=60), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poi_kind'), ['kind'], unique=False)

    op.create_table('alert_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.Column('rule', sa.String(length=24), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=240), nullable=False),
    sa.Column('acked', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_event_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_event_rule'), ['rule'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_event_ts'), ['ts'], unique=False)

    op.create_table('maint_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maint_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maint_record_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_maint_record_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maint_record_unit'), ['unit'], unique=False)

    op.create_table('org_setting',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('org_id', 'key')
    )
    op.create_table('report_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.Column('date_label', sa.String(length=16), nullable=False),
    sa.Column('block_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('n_reports', sa.Integer(), nullable=False),
    sa.Column('n_no_dvir', sa.Integer(), nullable=False),
    sa.Column('n_unsafe', sa.Integer(), nullable=False),
    sa.Column('fleet_safe_pct', sa.Float(), nullable=False),
    sa.Column('groups_json', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_block', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_block_org_id'), ['org_id'], unique=False)

    op.create_table('tms_driver',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.Column('driver_company', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('pay_type', sa.String(length=16), nullable=False),
    sa.Column('pay_pct', sa.Float(), nullable=False),
    sa.Column('truck', sa.String(length=32), nullable=False),
    sa.Column('trailer', sa.String(length=32), nullable=False),
    sa.Column('hired_date', sa.String(length=12), nullable=False),
    sa.Column('emergency_name', sa.String(length=120), nullable=False),
    sa.Column('emergency_phone', sa.String(length=40), nullable=False),
    sa.Column('cdl_exp', sa.String(length=12), nullable=False),
    sa.Column('med_exp', sa.String(length=12), nullable=False),
    sa.Column('mvr_exp', sa.String(length=12), nullable=False),
    sa.Column('chouse_exp', sa.String(length=12), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('tms_driver', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tms_driver_org_id'), ['org_id'], unique=False)

    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('unit_type', sa.String(length=16), nullable=False),
    sa.Column('subtype', sa.String(length=40), nullable=False),
    sa.Column('terminal', sa.String(length=40), nullable=False),
    sa.Column('customer', sa.String(length=120), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.Column('vin', sa.String(length=20), nullable=False),
    sa.Column('year', sa.String(length=8), nullable=False),
    sa.Column('make', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('fleet_no', sa.String(length=40), nullable=False),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('plate_state', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_unit'), ['unit'], unique=False)

    op.create_table('unit_doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=140), nullable=False),
    sa.Column('stored', sa.String(length=200), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit_doc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_doc_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_doc_unit'), ['unit'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('pw_hash', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('account', sa.String(length=60), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_org_id'), ['org_id'], unique=False)

    op.create_table('work_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('invoiced_at', sa.DateTime(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('complaint', sa.Text(), nullable=False),
    sa.Column('mechanic', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_pm', sa.Boolean(), nullable=False),
    sa.Column('pm_miles', sa.Integer(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('service_date', sa.String(length=10), nullable=True),
    sa.Column('waiting_parts', sa.Boolean(), nullable=False),
    sa.Column('campaign', sa.String(length=12), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('invoice_number', sa.String(length=40), nullable=False),
    sa.Column('po_number', sa.String(length=60), nullable=False),
    sa.Column('authorizer', sa.String(length=80), nullable=False),
    sa.Column('shop_invoice', sa.String(length=60), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_unit'), ['unit'], unique=False)

    op.create_table('block_driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('driver', sa.String(length=128), nullable=False),
    sa.Column('is_no_dvir', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['report_block.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('block_driver', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_block_driver_org_id'), ['org_id'], unique=False)

    op.create_table('defect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.Column('block_date', sa.Date(), nullable=False),
    sa.Column('date_label', sa.String(length=16), nullable=False),
    sa.Column('driver', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('unit_kind', sa.String(length=16), nullable=False),
    sa.Column('dvir_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('mechanic', sa.String(length=128), nullable=False),
    sa.Column('mechanic_notes', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['report_block.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('defect', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defect_org_id'), ['org_id'], unique=False)

    op.create_table('part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('on_hand', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_part_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_part_number'), ['part_number'], unique=False)

    op.create_table('work_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('part_number', sa.String(length=60), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_line_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_line_org_id'))

    op.drop_table('work_order_line')
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_part_number'))
        batch_op.drop_index(batch_op.f('ix_part_org_id'))

    op.drop_table('part')
    with op.batch_alter_table('defect', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defect_org_id'))

    op.drop_table('defect')
    with op.batch_alter_table('block_driver', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_block_driver_org_id'))

    op.drop_table('block_driver')
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_unit'))
        batch_op.drop_index(batch_op.f('ix_work_order_status'))
        batch_op.drop_index(batch_op.f('ix_work_order_org_id'))

    op.drop_table('work_order')
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_org_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_name'))

    op.drop_table('vendor')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_org_id'))

    op.drop_table('user')
    with op.batch_alter_table('unit_doc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_doc_unit'))
        batch_op.drop_index(batch_op.f('ix_unit_doc_org_id'))

    op.drop_table('unit_doc')
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_unit'))
        batch_op.drop_index(batch_op.f('ix_unit_org_id'))

    op.drop_table('unit')
    with op.batch_alter_table('tms_driver', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tms_driver_org_id'))

    op.drop_table('tms_driver')
    with op.batch_alter_table('report_block', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_block_org_id'))

    op.drop_table('report_block')
    op.drop_table('org_setting')
    with op.batch_alter_table('maint_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maint_record_unit'))
        batch_op.drop_index(batch_op.f('ix_maint_record_org_id'))
        batch_op.drop_index(batch_op.f('ix_maint_record_kind'))

    op.drop_table('maint_record')
    with op.batch_alter_table('alert_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_event_ts'))
        batch_op.drop_index(batch_op.f('ix_alert_event_rule'))
        batch_op.drop_index(batch_op.f('ix_alert_event_org_id'))

    op.drop_table('alert_event')
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poi_kind'))

    op.drop_table('poi')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_slug'))

    op.drop_table('organization')
    # ### end Alembic commands ###
